version: '3.5'

services:
  app:
    build:
      context: .
    volumes:
      - ./migrations:/app/migrations
      - ./seeds:/app/seeds
      - ./server:/app/server
    ports:
      - 3000:3000
    command: npm start

#   db:
#     image: postgres:9.6-alpine
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#       POSTGRES_DB: cashback
#     volumes:
#       - ./postgres-data:/var/lib/postgresql/data
#     ports:
#       - '5432:5432'